modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/RayTrace082/untamedwilds/issues"

[[mods]]
modId="untamedwilds"
version="1.21.1-3.0.1"
displayName="Untamed Wilds"
displayURL="https://github.com/RayTrace082/untamedwilds/"
logoFile="logo.png"
authors="RayTrace082, Raguto"
description='''Expanding on the natural world of Minecraft.'''

[[dependencies.untamedwilds]]
    modId="citadel"
    mandatory=true
    versionRange="[2.7.5]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.untamedwilds]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"
